apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos-dep
  namespace: fast-order
  labels:
    app: pagamentos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamentos-api
  template:
    metadata:
      labels:
        app: pagamentos-api
    spec:
      containers:
      - name: pagamentos-api-cont
        image: sickbanger/pagamentos-api:latest
        ports:
        - containerPort: 5271
        - containerPort: 7205
        envFrom:
          - configMapRef:
              name: pagamentos-api-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 5271
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5271
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
