apiVersion: v1
kind: Service
metadata:
  name: pagamentos-api-svc
  namespace: fast-order
spec:
  selector:
    app: pagamentos-api
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 5271
    - port: 443
      name: https
      targetPort: 7205
